timezone: "America/New York"

url: "minerobbersprojects.github.io"
baseurl: "/towntheme"
# change previous two lines for tilde.town usage

name: "tilde.town Jekyll theme"

css:
  bgcolor: pink
  font-family: courier
